blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls', namespace='post')), 
    path('', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('', views.home, name='home-page'),
    path('post/<slug:slug>/<int:year>/<int:month>/<int:day>', views.DetailView, name='post-page'),
    path('createpost', views.CreatePostView, name='createpost-page'),
    path('<slug:blogger>/myposts', views.MyPostsView, name='myposts-page'),
    path('<slug:slug>/<int:year>/<int:month>/<int:day>/edit', views.UpdatePostView, name='updatepost-page'),
    path('delete/<int:id>', views.DeleteView, name='delete-page')
]

users/urls.py
from django.urls import path
from .views import RegisterView, UpdateProfileView, BeAuthorView
from django.contrib.auth.views import LoginView, LogoutView
app_name = 'users'
urlpatterns = [
    path('register/',RegisterView, name='register-page'),
    path('login/', LoginView.as_view(template_name='users/login.html') , name='login-page'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout-page'),
    path('profile', UpdateProfileView, name='profile-page'),
    path('be-author', BeAuthorView, name='beauthor-page')
]

post/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from autoslug import AutoSlugField
from autoslug.settings import slugify as default_slugify
from users.models import Author
from PIL import Image



def custom_slugify(value):
    return default_slugify(value).replace(' ', '-')



class published_posts(models.Manager):
    def get_queryset(self):
        # if super().get_queryset() == None:
        #     super().get_queryset()
        # else:
        return super().get_queryset().filter(status='p')
        
class Post(models.Model):
    STATUS_CHOICES = (('p', 'Published'), ('d', 'Draft'))
    title = models.CharField('post title', max_length=50)
    slug = AutoSlugField(populate_from='title', unique_for_date='published', slugify=custom_slugify)
    body = models.TextField('post body')
    image = models.ImageField('post image', upload_to='post/posts/', blank=True)
    thum_image = models.ImageField('Thumb image', upload_to='post/posts/', blank=True, default='post/posts/default-thumbnail.jpg' )
    created = models.DateTimeField(auto_now_add=True)
    published = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField( 'post status', max_length=50, choices=STATUS_CHOICES)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='posts')
    objects = models.Manager()
    pub_posts = published_posts()
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.thum_image.path)
        output = (300, 174)
        if img.height > 300 and img.width >300:
            img.thumbnail(output)

            img.save(self.thum_image.path)

    class Meta:
        ordering = ['-published']
    
    def get_absolute_url(self):
        return reverse('post:post-page', kwargs={'slug':self.slug,
                                                 'year': self.published.year,
                                                 'month': self.published.month,
                                                 'day': self.published.day})
    def get_update_url(self):
        return reverse('post:updatepost-page', kwargs={'slug':self.slug,
                                                 'year': self.published.year,
                                                 'month': self.published.month,
                                                 'day': self.published.day})
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    created = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-created']
    def __str__(self):
        return self.body[:20]

class CommentReply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='replies')
    body = models.TextField()
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    
    def __str__(self):
        return f'reply on {self.comment} of {self.comment.post}'







        

post/forms.py
from .models import Post, Comment, CommentReply
from django import forms

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields =['title', 'body', 'image', 'thum_image', 'status']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
   
    
class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = CommentReply
        fields = ['body']

post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Post, Comment, CommentReply
from .forms import CreatePostForm, CommentForm, CommentReplyForm
from django.core.paginator import Paginator
from django import forms

def home(request):
    query_list = Post.pub_posts.all()
    paging = Paginator(query_list, 4)
    page = request.GET.get('page', 1)
    posts = paging.page(page)
    return render(request, 'post/home.html', {'posts': posts})

@login_required
def DetailView(request, slug, year, month, day):
    post = get_object_or_404(Post, slug=slug, 
                                   published__year=year,
                                   published__month=month,
                                   published__day=day )
   
    
    
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save
            newcom = form.save(commit=False)
            newcom.user = request.user
            newcom.post = post
            newcom.save()
            form = CommentForm()
    else:
        form = CommentForm()
    return render(request, 'post/detail.html', {'post': post, 'form':form})

@login_required
def CreatePostView(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST,request.FILES)
        if form.is_valid():
            ins = form.save(commit=False)
            ins.author = request.user.profile.author
            ins.save()
            
            return redirect('post:home-page')
    else:
        form = CreatePostForm()

    return render(request, 'post/createpost.html', {'form': form})

@login_required
def DeleteView(request, id):
    post = get_object_or_404(Post, id=id)
    if request.user == post.author.profile.user:
        if request.method == 'POST':
            post.delete()
            next = request.GET.get('next', None)
            if next == None:
                return redirect('post:home-page' )
            else:
                return redirect(next)
    warning = 'Your are not allowed to be here !'
    return render(request, 'post/delete.html', {'post': post, 'warning': warning, 'from':request.GET.get('from', None)})


@login_required
def MyPostsView(request, blogger):
    blogger = User.objects.get(username=blogger)
    return render(request, 'post/myposts.html', {'blogger':blogger})

@login_required
def UpdatePostView(request, slug, year, month, day):
    if request.method == 'POST':
        form = CreatePostForm(request.POST,request.FILES, instance=request.user.profile.author.posts.get( slug=slug, 
                                                                                                        published__year=year,
                                                                                                        published__month=month,
                                                                                                        published__day=day))
        if form.is_valid():
            form.save()
            return redirect('post:myposts-page', blogger=request.user)
    else:
        form = CreatePostForm(instance=request.user.profile.author.posts.get( slug=slug, 
                                                                              published__year=year,
                                                                              published__month=month,
                                                                              published__day=day))

    return render(request, 'post/createpost.html', {'form': form})

post/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel=stylesheet href="{% static 'post/css/bootstrap.min.css' %}">
    <link rel=stylesheet href="{% static 'post/css/style.css' %}">
    
    <title>{%block title%}{% endblock %}</title>
</head>
<body>
        {%if messages%}
        {%for message in messages%}
        <div class="alert alert-dismissible alert-{{message.tags}}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{message}}
        </div>
    
        
        
    
        {%endfor%}
        {%endif%}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{%url 'post:home-page'%}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Pricing</a>
                    </li>
                    {%url 'users:login-page' as loginurl%}
                    {%if not user.is_authenticated and request.path != loginurl%}
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'users:login-page'%}">LogIn</a>
                    </li>
                    {%endif%}
                    {%if user.is_authenticated%}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" href="{%url 'users:profile-page'%}" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{user.username}}</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            {%if not user.profile.author%}
                                <a class="dropdown-item" href="{%url 'users:beauthor-page'%}">Become an author</a>
                            {%else%}
                                <a class="dropdown-item" href="{%url 'post:createpost-page'%}">Create Post</a>
                                <a class="dropdown-item" href="{%url 'post:myposts-page' user.username%}">My Posts</a>
                            {%endif%}
                                <a class="dropdown-item" href="{%url 'users:logout-page'%}">Logout </a>
                        </div>
                    </li>
                    {%endif%}
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
      
           
          
           
        <div class="container">
    {%block body%}
    the body of the pages exists here
    {% endblock %}
    </div>
    

   
    
        <script src="{%static 'post/js/jquery.js' %}"></script> 
        <script src="{%static 'post/js/propper.js' %}"></script> 
        <script src="{%static 'post/js/bootstrap.js' %}"></script>                     
</body>
</html>