blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls', namespace='post')), 
    path('', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('', views.home, name='home-page'),
    path('post/<slug:slug>/<int:year>/<int:month>/<int:day>', views.DetailView, name='post-page'),
    path('createpost', views.CreatePostView, name='createpost-page'),
    path('<slug:blogger>/myposts', views.MyPostsView, name='myposts-page'),
    path('<slug:slug>/<int:year>/<int:month>/<int:day>/edit', views.UpdatePostView, name='updatepost-page'),
    path('delete/<int:id>', views.DeleteView, name='delete-page')
]

post/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from autoslug import AutoSlugField
from autoslug.settings import slugify as default_slugify
from users.models import Author
from PIL import Image



def custom_slugify(value):
    return default_slugify(value).replace(' ', '-')



class published_posts(models.Manager):
    def get_queryset(self):
        # if super().get_queryset() == None:
        #     super().get_queryset()
        # else:
        return super().get_queryset().filter(status='p')
        
class Post(models.Model):
    STATUS_CHOICES = (('p', 'Published'), ('d', 'Draft'))
    title = models.CharField('post title', max_length=50)
    slug = AutoSlugField(populate_from='title', unique_for_date='published', slugify=custom_slugify)
    body = models.TextField('post body')
    image = models.ImageField('post image', upload_to='post/posts/', blank=True)
    thum_image = models.ImageField('Thumb image', upload_to='post/posts/', blank=True, default='post/posts/default-thumbnail.jpg' )
    created = models.DateTimeField(auto_now_add=True)
    published = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField( 'post status', max_length=50, choices=STATUS_CHOICES)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='posts')
    objects = models.Manager()
    pub_posts = published_posts()
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.thum_image.path)
        output = (300, 174)
        if img.height > 300 and img.width >300:
            img.thumbnail(output)

            img.save(self.thum_image.path)

    class Meta:
        ordering = ['-published']
    
    def get_absolute_url(self):
        return reverse('post:post-page', kwargs={'slug':self.slug,
                                                 'year': self.published.year,
                                                 'month': self.published.month,
                                                 'day': self.published.day})
    def get_update_url(self):
        return reverse('post:updatepost-page', kwargs={'slug':self.slug,
                                                 'year': self.published.year,
                                                 'month': self.published.month,
                                                 'day': self.published.day})
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    created = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-created']
    def __str__(self):
        return self.body[:20]

class CommentReply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='replies')
    body = models.TextField()
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    
    def __str__(self):
        return f'reply on {self.comment} of {self.comment.post}'







        

post/forms.py
from .models import Post, Comment, CommentReply
from django import forms

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields =['title', 'body', 'image', 'thum_image', 'status']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
   
    
class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = CommentReply
        fields = ['body']

post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Post, Comment, CommentReply
from .forms import CreatePostForm, CommentForm, CommentReplyForm
from django.core.paginator import Paginator
from django import forms

def home(request):
    query_list = Post.pub_posts.all()
    paging = Paginator(query_list, 4)
    page = request.GET.get('page', 1)
    posts = paging.page(page)
    return render(request, 'post/home.html', {'posts': posts})

@login_required
def DetailView(request, slug, year, month, day):
    post = get_object_or_404(Post, slug=slug, 
                                   published__year=year,
                                   published__month=month,
                                   published__day=day )
   
    
    
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save
            newcom = form.save(commit=False)
            newcom.user = request.user
            newcom.post = post
            newcom.save()
            form = CommentForm()
    else:
        form = CommentForm()
    return render(request, 'post/detail.html', {'post': post, 'form':form})

@login_required
def CreatePostView(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST,request.FILES)
        if form.is_valid():
            ins = form.save(commit=False)
            ins.author = request.user.profile.author
            ins.save()
            
            return redirect('post:home-page')
    else:
        form = CreatePostForm()

    return render(request, 'post/createpost.html', {'form': form})

@login_required
def DeleteView(request, id):
    post = get_object_or_404(Post, id=id)
    if request.user == post.author.profile.user:
        if request.method == 'POST':
            post.delete()
            next = request.GET.get('next', None)
            if next == None:
                return redirect('post:home-page' )
            else:
                return redirect(next)
    warning = 'Your are not allowed to be here !'
    return render(request, 'post/delete.html', {'post': post, 'warning': warning, 'from':request.GET.get('from', None)})


@login_required
def MyPostsView(request, blogger):
    blogger = User.objects.get(username=blogger)
    return render(request, 'post/myposts.html', {'blogger':blogger})

@login_required
def UpdatePostView(request, slug, year, month, day):
    if request.method == 'POST':
        form = CreatePostForm(request.POST,request.FILES, instance=request.user.profile.author.posts.get( slug=slug, 
                                                                                                        published__year=year,
                                                                                                        published__month=month,
                                                                                                        published__day=day))
        if form.is_valid():
            form.save()
            return redirect('post:myposts-page', blogger=request.user)
    else:
        form = CreatePostForm(instance=request.user.profile.author.posts.get( slug=slug, 
                                                                              published__year=year,
                                                                              published__month=month,
                                                                              published__day=day))

    return render(request, 'post/createpost.html', {'form': form})

post/templates/post/createpost.html
{%extends 'base.html' %}
{%block title%}
Create Post
{%endblock%}
{%block body%}
{%if not user.profile.author.posts.all%}
create your first post 
{%endif%}
<form method="POST" action="" enctype="multipart/form-data">{%csrf_token%}
        {{form.as_p}}
    <button type="submit"> Submit </button>
</form>
{%endblock%}

post/templates/post/delete.html
{%extends 'base.html'%}
{%block title%}
delete ?{{post.title}}
{%endblock%}
{%block body%}
{% if user == post.author.profile.user%}
<form method="POST" action="{%if from%}?next={{from}}{%endif%}">
    {%csrf_token%}
    Warning --- the following will be deleted:<br>
     {{post.title}}<br>
    <input type="submit" value="Confirm">
</form>
{%else%}
<h3> {{user.profile}} {{warning}}</h3>
{%endif%}
{%endblock%}

post/templates/post/detail.html
{%extends 'base.html'%}
{%block title%}
{{post.title}}
{%endblock%}
{%block body%}

<h1 class="text-center">{{post.title}}</h1>

    <div class="row">
        <div class="blog col-md-9">        
            <div class="card">
                <a href="#">
                  {%if post.image%}
                <img src="{{post.image.url}}" class="card-img-top" alt="blog1"></a>
                  {%endif%}
                <div class="card-body">
                <h3 class="card-title text-center">
                  
                </h3>
                <div class="blog-header">
                    <h1 class="blog-title">{{post.title}}</h1>
                    <p class="lead blog-description">{{post.body}}</p>
                  </div>
            
                  <div class="row">
            
                    <div class="col blog-main">
            
                      <div class="blog-post">
                        <h2 class="blog-post-title">Post breif</h2>
                        <p class="blog-post-meta">{{post.published}} <a href="{%url 'post:myposts-page' blogger=post.author.profile.user.username%}">{{post.author}}</a></p>
            
                       
                        
                      </div><!-- /.blog-post -->
            
                      
            
                    </div><!-- /.blog-main -->
            
            
                  </div><!-- /.row -->
                <p class="card-text"></p>
                </div>
            </div>          
        </div>
        <div class="container">
        {%for comment in post.comments.all %}
        <p class="row display-5" style="display: block; ">{{comment.user}}</p>
          <p class="row display-5" style="display: block; ">__{{comment.body}}</p>
        {%endfor%}
        <form method="POST" action="">
          {%csrf_token%}
          {{form.as_p}}
          <button type="submit">Comment</button>
        </form>
      </div>
{%endblock%}

post/templates/post/home.html
{%extends 'base.html' %}
{%load static%}
{% block title %}
home page
{% endblock %}

{%block body%}


{%for post in posts%}
<div class="row">
<div class="jumbotron  col-md-11">
    
    <div class="online">
      <a href="{{post.get_absolute_url}}"><img class=" resize"  src="{{post.thum_image.url}}" alt="Card image"></a>
    <h1><a href="{{post.get_absolute_url}}"> {{post.title}}</a></h1>
    <p class="lead">{{post.body|linebreaks|truncatechars:80}}</p>
    <footer class="blockquote-footer ">Written By <cite title="Source Title"><h6 style="display:inline"><a  href="{%url 'post:myposts-page' post.author.profile.user.username%}"> {{post.author.profile.user.username}}</a></h6></cite></footer>
   </div>
   <div class="clear"></div>
    <hr class="my-3">
    
   
    <p class="lead leead">
      <a class="btn btn-primary btn-lg" href="{{post.get_absolute_url}}" role="button">Read More</a>
      {%if post.author.profile.user.username == user.username %}
      <a class="btn btn-lg  btn-outline-warning" href="{{post.get_update_url}}" role="button">Edit</a>
      
      {%endif%}
      
    </p>
  </div>
</div>

{%endfor%}

<div style="text-align:center;">
    {%if posts.paginator%}
  <div>
    <ul class="pagination pagination-lg">
      {%if posts.has_previous%}
      <li class="page-item ">
        <a class="page-link" href="?page=1">&laquo;First</a>
      </li>
      <li class="page-item ">
        <a class="page-link" href="?page={{posts.previous_page_number}}">Previous</a>
      </li>
      {%endif%}
      {% for num in posts.paginator.page_range%}
      {%if num == posts.number%}
      <li class="page-item active">
          <a class="page-link" href="?page={{num}}">{{num}}</a>
        </li>
      {%elif num > posts.number|add:'-3' and num < posts.number|add:'3'%}
      
      <li class="page-item">
          <a class="page-link" href="?page={{num}}">{{num}}</a>
        </li>
      {%endif%}
      {%endfor%}
      {%if posts.has_next%}
     
      <li class="page-item">
        <a class="page-link" href="?page={{posts.next_page_number}}">Next</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{posts.paginator.num_pages}}">&raquo;Last</a>
      </li>
      {%endif%}
    </ul>
  </div>
  {%endif%}
</div>

{% endblock %}

post/templates/post/myposts.html
{%extends 'base.html'%}
{%block title%}
my posts
{%endblock%}
{%block body%}
{%for post in blogger.profile.author.posts.all%}
<section class='container-fluid'>
        <div class="row">
        <div class="blog col-md-9">        
                <div class="card">
                    <a href="{{post.get_absolute_url}}">
                    <img src="{{post.thum_image.url}}" class="card-img-top" alt="blog1"></a>
                    <div class="card-body">
                    <h3 class="card-title text-center">
                      
                          <a href="{{post.get_absolute_url}}"> {{post.title}}</a>
                    </h3>
                    <p class="text-justify">
                      {{post.body}}
                    </p>
                    <p class="card-text"></p>
                    </div>
                    <div class="card-footer text-center">
                    <a href="{{post.get_absolute_url}}"><button type="button" class="btn btn-primary">Read More</button></a>
                    {%if blogger.username == user.username %}
                    <a href="{{post.get_update_url}}"><button type="button" class="btn btn-primary">Edit</button></a>
                    <a href="{%url 'post:delete-page' post.id%}?from={{request.path|urlencode}}"><button type="button" class="btn btn-danger">Remove</button></a>
                    {%endif%}
                    </div>
                </div>          
            </div>
            </section>
{%endfor%}
{%endblock%}