blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls', namespace='post')), 
    path('', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, UpdateProfileView, BeAuthorView
from django.contrib.auth.views import LoginView, LogoutView
app_name = 'users'
urlpatterns = [
    path('register/',RegisterView, name='register-page'),
    path('login/', LoginView.as_view(template_name='users/login.html') , name='login-page'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout-page'),
    path('profile', UpdateProfileView, name='profile-page'),
    path('be-author', BeAuthorView, name='beauthor-page')
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    SEX_CHOICES = (('M', 'Male'), ('F', 'Female'))
    first_name = models.CharField('First Name', max_length=20, blank=True)
    last_name = models.CharField('Last Name', max_length=20, blank=True)
    image = models.ImageField('Personal Image', upload_to='post/profile/', default='post/profile/profile.jpg')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    sex = models.CharField(choices=SEX_CHOICES, max_length=20, blank=True)

    def save(self, *args, **kwargs):
        
        if self.first_name == '':
            self.first_name = self.user.first_name
            self.last_name = self.user.last_name
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def __str__(self):
        return self.first_name + self.last_name


class Author(models.Model):
    bio = models.TextField('description (bio)', blank=True)
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.profile.first_name} {self.profile.last_name}'

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile, Author


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    username = forms.CharField(max_length=20)
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('the email is already exist')
        return email
    
class ProfileForm(forms.ModelForm): 
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'image', 'sex']
    
class BeAuthorForm(forms.ModelForm):
    class Meta:
        model= Author
        fields = ['bio']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from .forms import RegisterForm, ProfileForm, BeAuthorForm
from django.contrib import messages

# Create your views here.



def RegisterView(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            name = form.cleaned_data['first_name'] + form.cleaned_data['last_name']
            messages.success(request, f'Account Created succefully {name}')
            username = form.cleaned_data['username']
            password = form.cleaned_data['password2']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('users:profile-page')
    else:
        form = RegisterForm()
    
    return render(request, 'users/register.html', {'form': form})


@login_required
def UpdateProfileView(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES,instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('post:home-page')
        
    else:
        form = ProfileForm(instance=request.user.profile)
    return render(request, 'users/profile.html', {'form': form})


@login_required
def BeAuthorView(request):
    if request.method == 'POST':
        form = BeAuthorForm(request.POST)
        if form.is_valid():
            ins = form.save(commit=False)
            ins.profile = request.user.profile
            ins.save()
            return redirect('post:createpost-page')
    else:
        form = BeAuthorForm()
    
    return render(request, 'users/beauthor.html', {'form': form})

users/templates/users/beauthor.html
{%extends 'base.html'%}
{%block title%}
Be an Author now!
{%endblock%}
{%block body%}
<form method="POST" action="">{%csrf_token%}
        {{form.as_p}}
    <button type="submit"> Send </button>
</form>
{%endblock%}

users/templates/users/login.html
{%extends 'base.html'%}
{%block title%}
Login
{%endblock%}
{%block body%}
<form method="POST" action="{%url 'users:login-page'%}">{%csrf_token%}


{{form.as_p}}
<button type="submit">Login</button>
</form>
<span class="display-5">Don't have an account!</span>
<span class="display-5"><a href="{% url 'users:register-page' %}">Register</a></span>
{%if next%}

    
<div class="display-5">you will be redirected to your destination after logining in</div>
   
{%endif%}
{%endblock%}

users/templates/users/logout.html
{%extends 'base.html'%}
{%block title%}
{%endblock%}
{%block body%}
<h1 class="display-1">You have Logedout successfully</h1>
{%endblock%}

users/templates/users/profile.html
{%extends 'base.html'%}
{%block title%}
Profile
{%endblock%}
{%block body%}
{{user.profile}}
<hr>
{% if not user.profile.sex or user.profile.sex == ''%}
<img class="widthSet heightSet" src='{{user.profile.image.url}}'>complete your profile
{%else%}
<img class="widthSet heightSet" src='{{user.profile.image.url}}'> update your information
{%endif%}
<form method="POST" action="" enctype="multipart/form-data">{%csrf_token%}
        {{form.as_p}}
    <button type="submit"> Update </button>
</form>


{%endblock%}

users/templates/users/register.html
{% extends 'base.html' %}
{% block title %}
Register 
{%endblock%}
{%block body%}
<form method='POST' action="">{%csrf_token%}
    {{form.as_p}}
    <button type="submit">Register</button>
</form>
{%endblock%}